hybrid_model:
  contributors:
    - Reda ElGhawi
    - Kraft, Basil
    - Reimers, Christian
    - Reichstein, Markus
    - Körner, Marco
    - Gentine, Pierre
    - Winkler, Alexander J
  date: null
  description: "Hybrid modeling of evapotranspiration: inferring stomatal and aerodynamic resistances using combined physics-based and machine learning"
  documentation: "ElGhawi, R., Kraft, B., Reimers, C., Reichstein, M., Körner, M., Gentine, P., & Winkler, A. J. (2023). Hybrid modeling of evapotranspiration: inferring stomatal and aerodynamic resistances using combined physics-based and machine learning. Environmental Research Letters, 18(3), 034039"
  identifier: https://doi.org/10.1088/1748-9326/ACBBE0
  keywords:
    - hybrid model
    - latent variables
    - machine learning
  license: MIT
  name: Hybrid Model
  url: https://github.com/relghawi/Hybrid_ET.git
  version: 1.0.0
  ml_process: Feed-forward Nwural Network
  host_physics: Penman Monteith
  latent_variables:
    - name: rs
      description: stomatal resistance
    - name: ra
      description: aerodynamic rsistance

physics_based_components:
  - description: "Penman-Monteith"
    documentation:
      - "Monteith J L 1965 Evaporation and environment Symp. Society for Experimental Biology, the State and Movement ofWater in Living Organisms vol 19, ed G E Fogg pp 205–34"
      - "Penman H L 1948 Natural evaporation from open water, hare soil and grass Proc. R. Soc. A 193 120–45"
    keywords:
      - "Physics-based"
    name: "Penman-Monteith"
    fixed_parameters_count: 9
    tunable_parameters_count: 2
    state_varialbles_count: 0
    resolution:
      temporal: Half-hourly
    lateral_flow: false

machine_learning_components:
  - description: Feed-forward Neural Network
    documentation: "ElGhawi, R., Kraft, B., Reimers, C., Reichstein, M., Körner, M., Gentine, P., & Winkler, A. J. (2023). Hybrid modeling of evapotranspiration: inferring stomatal and aerodynamic resistances using combined physics-based and machine learning. Environmental Research Letters, 18(3), 034039"
    identifier: https://doi.org/10.1088/1748-9326/ACBBE0
    keywords:
      - latent variables
      - machine learning
    license: MIT
    name: FNN
    url: https://github.com/relghawi/Hybrid_ET.git
    version: 1.0.0
    ml_process: Feed-forward Nwural Network

#### Multiple NNs, for mutliple targets/latents
    # If type == "NN"
    nn_type: FNN
    nn_name: FNN-rs
    number_layers: 4
    num_nodes: 32
    batch_size: 2000
    learning_rate: 0.0005
    number_predictors: 1
    activation_function:
    - Sofplus
    - ReLU
    input_scaling: Normalization Mean-Std
    initialization: Random initialization
    loss_function: Mean Absolute Error
    regularization: None
    optimization_method: AdamW
    host_physics_model: Penman-Monteith
    target_variable:
    - Latent Heat FLux
    - Sensible Heat FLux
    training_requirements: GPU/CPU
    training_resources:
      compute_time: N/A
      memory: N/A
      storage: N/A
      gpu_ID: A40 ## parallelization
      gpu_num : 1
      cpu_ID: N/A
      cpu_num: N/A
      software: Python
    # End if type == "NN"


    nn_type: FNN
    nn_name: FNN-ra
    number_layers: 2
    num_nodes: 32
    batch_size: 2000
    learning_rate: 0.0005
    number_predictors: 1
    activation_function:
    - Sofplus
    - ReLU
    input_scaling: Normalization Mean-Std
    initialization: Random initialization
    loss_function: Mean Absolute Error
    regularization: None
    optimization_method: AdamW
    host_physics_model: Penman-Monteith
    target_variable:
    - Latent Heat FLux
    - Sensible Heat FLux
    training_requirements: GPU/CPU
    training_resources:
      compute_time: N/A
      memory: N/A
      storage: N/A
      gpu_ID: A40 ## parallelization
      gpu_num : 1
      cpu_ID: N/A
      cpu_num: N/A
      software: Python
    # End if type == "NN"

# Data
data:
  ## Input Data
  inputs:
    - name: Net Radiation
      format: Rn
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      precision: Raw data
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly

    - name: Vapor Pressure Deficit
      format: VPD
      extent:
        min: 0
        max: 5
      source: FLUXNET2015
      quality: Raw data
      units: kPa
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly

    - name: Shortwave Incoming
      format: SWin
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly

    - name: mean incoming shortwave potential
      format: SW_pot_sm
      extent:
        min: N/A
        max: N/A
      source: Calculated
      quality: Raw data
      units: W/m^2
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly


    - name: Air temperarture
      format: TA
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: degrees Celsius
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly


    - name: Water Availability Index
      format: WAI
      extent:
        min: N/A
        max: N/A
      source: Calculated
      quality: Raw data
      units: "-"
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly


    - name: Wind Speed
      format: WS
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: "-"
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly

  outputs:
    - name: Latent Heat FLux
      format: LE
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly

    - name: Sensible Heat FLux
      format: H
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      precision: ""
      scale: ""
      offset: ""
      resolution:
        spatial: ""
        temporal: Half-hourly
