hybrid_model:
  contributors:
    - Reda ElGhawi
    - Kraft, Basil
    - Reimers, Christian
    - Reichstein, Markus
    - Körner, Marco
    - Gentine, Pierre
    - Winkler, Alexander J
  created: null
  description: "Hybrid modeling of evapotranspiration: inferring stomatal and aerodynamic resistances using combined physics-based
    and machine learning"
  documentation:
    - https://doi.org/10.1088/1748-9326/acbbe0
  identifier: https://doi.org/10.1088/1748-9326/acbbe0
  keywords:
    - hybrid model
    - latent variables
    - machine learning
  license: MIT
  name: Hybrid Model
  url: https://github.com/relghawi/Hybrid_ET.git
  version: 1.0.0
  ml_process: Feed-forward Nwural Network
  host_physics: Penman Monteith
  latent_variables:
    - name: rs
      description: stomatal resistance
    - name: ra
      description: aerodynamic rsistance

physics_based_components:
  - description: "Penman-Monteith"
    documentation:
      - "Monteith J L 1965 Evaporation and environment Symp. Society for Experimental Biology, the State and Movement ofWater
        in Living Organisms vol 19, ed G E Fogg pp 205–34"
      - "Penman H L 1948 Natural evaporation from open water, hare soil and grass Proc. R. Soc. A 193 120–45"
    keywords:
      - "Physics-based"
    name: "Penman-Monteith"
    fixed_parameters_count: 9
    tunable_parameters_count: 2
    state_varialbles_count: 0
    temporal_resolution: Half-hourly
    lateral_flow: false

machine_learning_components:
  - description: Feed-forward Neural Network
    keywords:
      - latent variables
      - machine learning
    license: MIT
    name: FNN
    url: https://github.com/relghawi/Hybrid_ET.git
    version: 1.0.0
    ml_process: Feed-forward Nwural Network
    # Multiple NNs, for multiple targets/latents
    neural_networks:
      - type: FNN
        name: FNN-rs
        layer_count: 4
        node_count: 32
        batch_size: 2000
        learning_rate: 0.0005
        predictor_count: 1
        activation_functions:
          - Sofplus
          - ReLU
        input_scaling: Normalization Mean-Std
        initialization: Random initialization
        loss_function: Mean Absolute Error
        regularization: None
        optimization_method: AdamW
        host_physics_model: Penman-Monteith
        target_variables:
          - Latent Heat FLux
          - Sensible Heat FLux
        training_requirements:
          cpu: true
          gpu: true
        training_resources:
          gpus:
            - model: A40
              count: 1
          software:
            - Python
      - type: FNN
        name: FNN-ra
        layer_count: 2
        node_count: 32
        batch_size: 2000
        learning_rate: 0.0005
        predictor_count: 1
        activation_functions:
          - Sofplus
          - ReLU
        input_scaling: Normalization Mean-Std
        initialization: Random initialization
        loss_function: Mean Absolute Error
        regularization: None
        optimization_method: AdamW
        host_physics_model: Penman-Monteith
        target_variables:
          - Latent Heat FLux
          - Sensible Heat FLux
        training_requirements:
          cpu: true
          gpu: true
        training_resources:
          gpus:
            - model: A40
              count: 1
          software:
            - Python

data:
  inputs:
    - name: Net Radiation
      encoding_format: Rn
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      precision: Raw data
      temporal_resolution: Half-hourly
    - name: Vapor Pressure Deficit
      encoding_format: VPD
      min_value: 0
      max_value: 5
      source: FLUXNET2015
      quality: Raw data
      units: kPa
      temporal_resolution: Half-hourly
    - name: Shortwave Incoming
      encoding_format: SWin
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      temporal_resolution: Half-hourly
    - name: mean incoming shortwave potential
      encoding_format: SW_pot_sm
      source: Calculated
      quality: Raw data
      units: W/m^2
      temporal_resolution: Half-hourly
    - name: Air temperarture
      encoding_format: TA
      source: FLUXNET2015
      quality: Raw data
      units: degrees Celsius
      temporal_resolution: Half-hourly
    - name: Water Availability Index
      encoding_format: WAI
      source: Calculated
      quality: Raw data
      units: "-"
      temporal_resolution: Half-hourly
    - name: Wind Speed
      encoding_format: WS
      source: FLUXNET2015
      quality: Raw data
      units: "-"
      temporal_resolution: Half-hourly
  outputs:
    - name: Latent Heat FLux
      encoding_format: LE
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      temporal_resolution: Half-hourly
    - name: Sensible Heat FLux
      encoding_format: H
      extent:
        min: N/A
        max: N/A
      source: FLUXNET2015
      quality: Raw data
      units: W/m^2
      temporal_resolution: Half-hourly
